//! Solid colours are native TextureSources generated by a GPU attachment clear.
//! The source clears only its assigned output region, so the renderer may place
//! it directly in an atlas. CPU sRGB conversion remains for decoded-image uploads.

use matcha_ecs::components::render::RenderCtx;
use render_interface::{
    PrepareOutputLayout, RegionRenderPassDescriptor, TextureDescriptor, TextureSource,
};

/// Gamma-encode a linear colour component for an sRGB texture source.
///
/// A render pass targeting an `Rgba8UnormSrgb` texture does this itself.
/// Raw texture upload is a byte copy and does not, so anything
/// uploading bytes by hand owes the conversion.
pub(crate) fn linear_to_srgb_u8(c: f32) -> u8 {
    let c = c.clamp(0.0, 1.0);
    let encoded = if c <= 0.0031308 {
        c * 12.92
    } else {
        1.055 * c.powf(1.0 / 2.4) - 0.055
    };
    (encoded * 255.0).round() as u8
}

/// Encode `color` as the bytes to upload for a tint pixel.
///
/// **Premultiplied**, and multiplied in *linear* space before the sRGB encode.
/// The pipeline blends with `PREMULTIPLIED_ALPHA_BLENDING`, so a translucent
/// colour written straight comes out too bright. Opaque fills are unaffected,
/// which is why the two text widgets got away without this for as long as they
/// did — the alpha they paint with is almost always 1.
pub(crate) fn premultiplied_srgb_bytes(color: [f32; 4]) -> [u8; 4] {
    let a = color[3].clamp(0.0, 1.0);
    [
        linear_to_srgb_u8(color[0] * a),
        linear_to_srgb_u8(color[1] * a),
        linear_to_srgb_u8(color[2] * a),
        (a * 255.0).round() as u8,
    ]
}

/// Define a lazy GPU-generated solid colour. No CPU pixel intermediate or
/// atlas placement is exposed to the widget.
pub(crate) fn solid_source(ctx: &RenderCtx, color: [f32; 4], what: &str) -> Option<TextureSource> {
    let _ = (ctx, what);
    let mut desc = TextureDescriptor::new([1, 1], wgpu::TextureFormat::Rgba8UnormSrgb);
    desc.usages = wgpu::TextureUsages::RENDER_ATTACHMENT;
    let a = color[3].clamp(0., 1.);
    Some(
        TextureSource::new(desc, move |mut c| {
            let _pass = c.target.region.begin_render_pass(
                &mut c.gpu,
                RegionRenderPassDescriptor {
                    load: wgpu::LoadOp::Clear(wgpu::Color {
                        r: (color[0] * a) as f64,
                        g: (color[1] * a) as f64,
                        b: (color[2] * a) as f64,
                        a: a as f64,
                    }),
                    ..Default::default()
                },
            )?;
            Ok(())
        })
        .with_output_layout(PrepareOutputLayout::AnyRegion),
    )
}
